FROM ghcr.io/mlflow/mlflow:latest

# Install required dependencies
RUN pip install pymysql cryptography 

# Install netcat
RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean && rm -rf /var/lib/apt/lists/* 