# Minimal configuration for Mimir
server:
  http_listen_port: 9009

# Storage configuration
blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/blocks
  tsdb:
    dir: /data/tsdb

# Distributor configuration
distributor:
  ring:
    kvstore:
      store: inmemory

# Ingester configuration
ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

# Compactor configuration
compactor:
  data_dir: /data/compactor
  sharding_ring:
    kvstore:
      store: inmemory 

auth_enabled: true
multitenancy_enabled: true