global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mlops_api'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Your FastAPI metrics endpoint
    metrics_path: '/metrics'

  - job_name: 'model_training'
    static_configs:
      - targets: ['host.docker.internal:8001']  # Metrics from your training processes
    metrics_path: '/metrics'

# Temporarily disabled until Mimir is properly configured
# remote_write:
#   - url: http://mimir:9009/api/v1/push
#     send_exemplars: true 