global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'yolo_trainer'
    static_configs:
      - targets: ['localhost:8000']
    scrape_interval: 5s  # More frequent scraping for training metrics
  - job_name: 'model_metrics'  # You might not need this if it's redundant
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
  - job_name: 'pushgateway'
    scrape_interval: 5s
    honor_labels: true  # This is important for Pushgateway
    static_configs:
      - targets: ['pushgateway:9091']